name: Tests

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - '.github/**'
      - 'src/**'
      - 'include/**'
      - 'examples/**'
      - 'test/**'
  push:
    branches:
      - main
      - dev
    paths:
      - '.github/**'
      - 'src/**'
      - 'include/**'
      - 'doc/**'

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: "Run test suite"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Ubuntu dependencies
      if: ${{ matrix.os == ubuntu-latest }}
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc valgrind

    # Shouldn't need to install dependencies for macos image; make and gcc
    # (linked to clang) should already be installed, while valgrind is not
    # supported.

    # Performed as separate step to more easily detect library build error
    - name: Build library
      run: |
        make lib

    - name: Run tests
      run: |
        ./runtests.sh
